export const ResponseMessage = {
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    USER_TYPE_INVALID: 'User type is invalid.',
    LOGIN_TYPE_INVALID: 'Login type is invalid.',
    PHONE_NUMBER_INVALID: 'Phone number is invalid.',
    PHONE_NUMBER_ALREADY_EXIST: 'Phone number already exists.',
    EMAIL_ALREADY_EXIST: 'Email already exists.',
    USER_REGISTER_SUCCESS: 'User registered successfully.',
    USER_LOGGEDIN_SUCCESS: 'User logged-in successfully.',
    PASSWORD_UPDATE_SUCCESS: 'Password updated successfully.',
    USER_NOT_EXIST: 'User does not exist.',
    CLIENT_NOT_EXIST: 'Client does not exist.',
    VENDOR_DATA_NOT_EXIST: 'Vendor data does not exist.',
    INCORRECT_PASSWORD: 'Incorrect password.',
    SAME_PASSWORD: 'You already have this password.',
    JOB_CREATE_SUCCESS: 'Job created successfully.',
    TOKEN_NOT_FOUND: 'Token not provided.',
    INVALID_TOKEN: 'Invalid or expired token.',
    DATA_SUCCESS: 'Success.',
    DATA_UPDATE_SUCCESS: 'Data updated successfully.',
    JOB_TASK_CREATE_SUCCESS: 'Task created successfully.',
    JOB_TASK_UPDATE_SUCCESS: 'Task updated successfully.',
    JOB_TASK_APPROVE_SUCCESS: 'Task approved successfully.',
    COMMENT_ADD_SUCCESS: 'Comment add successfully.',
    JOB_CANCEL_SUCCESS: 'Job cancelled successfully.',
    JOB_REPORT_SUCCESS: 'Job reported successfully.',
    FORGET_EMAIL_SUCCESS: 'An email has been sent with instructions to reset your password.',
    OTP_SUCCESS: 'An OTP has been sent to verify your email.',
    JOB_NOT_EXIST: 'Job does not exist.',
    CATEGORY_SUCCESS: 'Category added successfully.',
    CATEGORY_NOT_EXIST: 'Category does not exist.',
    SUB_CATEGORY_SUCCESS: 'Sub-category added successfully.',
    PROFILE_ALREADY_EXIST: 'Profile already exist.',
    PROFILE_NOT_EXIST: 'Profile does not exist.',
    PROFILE_SUCCESS: 'Profile created successfully.',
    OTP_SENT_SUCCESS: 'OTP sent successfully.',
    OTP_VERIFY_SUCCESS: 'OTP verified successfully.',
    WRONG_OTP: 'Wrong OTP.',
    EMAIL_NOT_VERIFIED: 'Email is not verifed yet, please verify before login.',
    SUBSCRIPTION_ALREADY_EXIST: 'You already have an active subscription.',
    SUBSCRIPTION_DUPLICATE_EXIST: 'The same subscription already exists.',
    ADDON_SERVICE_SUCCESS: 'Add-on service activated successfully with Stripe subscription.',
    TEAM_SERVICE_SUCCESS: 'Add team member service activated successfully with Stripe subscription.',
    SERVICE_NOT_EXIST: 'No active add-on service exists.',
    SERVICE_ALREADY_EXIST: 'Service item already exist..',
    SERVICE_ITEM_NOT_EXIST: 'Service item does not exist.',
    ADDON_SERVICE_CANCELLED: 'The add-on service has been cancelled.',
    NO_ACTIVE_SUBSCRIPTION_EXIST: 'No active susbcription exists.',
    CHECKOUT_SUCCESS: 'Stripe checkout session created successfully',
    SUBSCRIPTION_INACTIVE: 'Subscription is inactive or may have expired.',
    CHECKOUT_FAILED: 'Failed to create Stripe checkout session.',
    SUBSCRIPTION_NOT_AUTHORIZED: 'You are not authorized to subscribe.',
    SUBSCRIPTION_REQUIRED: 'Access denied. A subscription is required to access this content.',
    NOT_AUTHORIZED: 'Access denied. You are not authorized to access this content.',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    SUBSCRIPTION_ERROR: 'An error occurred while processing your subscription. Please try again later.',
    SUBSCRIPTION_SUCCESS: 'Subscription completed successfully.',
    SUBSCRIPTION_NOT_FOUND: 'No subscription found.',
    SUBSCRIPTION_FAILED: 'Failed to update subscription.',
    CARD_ATTACH_SUCCESS: 'Card attached successfully.',
    CARD_DETACH_SUCCESS: 'Card detached successfully.',
    CARD_DEFAULT_SUCCESS: 'The card has been set as the default successfully.',
    TEAM_ADD_SUCCESS: 'Team added successfully.',
    TEAM_DELETE_SUCCESS: 'Team deleted successfully.',
    JOB_NOT_ACTIVE: 'This job is no longer available.',
    JOB_ACTIVE_NO_CANCEL: 'You cannot cancel this job as it is currently active.',
    APPROVED_SUCCESS: 'Your request has been reviewed and approved successfully.',
    DECLINED_SUCCESS: 'Your request was declined. Contact support for assistance.',
    JOB_NOT_ACCESSIBLE: 'This job is not accepted or does not belong to you.',
    EDIT_JOB_REQ_EXIST: 'A pending edit job request already exists.',
    NO_EDIT_REQUEST: 'You cannot edit this job as it does not belong to you.',
    EDIT_REQUEST_SUCCESS: 'Your request has been updated and is currently under review.',
    JOB_NOT_CONFIRMED: 'This job is not confirmed or does not belong to you.',
    INVALID_ACTION: 'This is an invalid action.',
    DUPLICATE_ACTION: 'This action has already been taken.',
    DATA_NOT_EXIST: 'Data does not exist.',
    JOB_CLOSE_SUCCESS: 'The job has been closed successfully.',
    JOB_ALREADY_CLOSED: 'The job is already closed.',
    JOB_STILL_ACTIVE: 'You cannot add feedback until the job is closed.',
    JOB_CLOSED_NO_ACTION: 'The job is closed; you cannot perform any actions.',
    JOB_ACTION_NOT_EXIST: 'Job action data not found.',
    JOB_TASK_LIMIT_EXCEEDED: 'You cannot have more than 5 job tasks.',
    TASK_NOT_EXIST: 'The task no longer exists.',
    JOB_ACCEPT_REQUIRED: 'You cannot add feedback until the job is accepted.',
    VENDOR_CLOSE_JOB_ACTION: 'You cannot mark this job as closed until the vendor closes it.',
    JOB_VENDOR_NOT_FOUND: 'No vendor found for this job yet.',
    DESTINATION_AC_NOT_FOUND: 'Destination account not found for this vendor. Please check with Stripe Connect.',
    IMAGE_GENERATE_ERROR: 'Image generation failed, please try again.',
    PAYMENT_SUCCESS: 'Payment successful.',
    PAYMENT_ERROR: 'An error occurred during payment. Please try again.',
    USER_LOGGEDOUT_SUCCESS: 'User logged-out successfully.',
    AUTH_TOKEN_EXPIRED: 'Session Token has expired, please relogin to continue.',
    ACCOUNT_SETUP_INCOMPLETE: 'Setup incomplete. Missing fields:',
    ACCOUNT_SETUP_COMPLETE: 'Account setup is complete.',
    CUSTOMER_NOT_FOUND: 'Customer not found',
    JOB_ALREADY_REPORTED: 'This job has already been reported.',
    INVALID_API_TYPE: 'Api type is invalid.',
};

export const ConstantValues = {
    PROFILE_STATUS_0: 0,
    PROFILE_STATUS_1: 1,
    PROFILE_STATUS_2: 2,
    PROFILE_STATUS_3: 3,
    PROFILE_STATUS_4: 4,

    JOB_STATUS_PENDING: 'pending',
    JOB_STATUS_VENDOR_ACCEPT: 'vendor_accept',
    JOB_STATUS_VENDOR_REJECT: 'vendor_reject',
    JOB_STATUS_VENDOR_CANCEL: 'vendor_cancel',
    JOB_STATUS_VENDOR_CLOSED: 'vendor_closed',
    JOB_STATUS_CLIENT_CLOSED: 'client_closed',
    JOB_STATUS_CLIENT_CONFIRM: 'client_confirm',

    TYPE_INC: 'inc',
    TYPE_DEC: 'dec',
    
};